# Generated by Django 3.1.7 on 2021-03-24 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0002_auto_20210325_0350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='username',
        ),
    ]
