# Generated by Django 3.1.7 on 2021-03-24 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0004_auto_20210325_0403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='fnmae',
            new_name='fname',
        ),
    ]
